<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    protected $fillable = ['kode', 'nama'];

    public static function all($columns = ['*'])
    {
        return parent::all($columns); // TODO: Change the autogenerated stub
    }

    use HasFactory;
}
